name: dash_router
repository: https://github.com/example/dash_router

packages:
  - packages/**
  - example
  - examples/**

command:
  version:
    workspaceChangelog: true

  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run static analysis on all packages

  test:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run tests in all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  build_runner:
    run: melos exec -- dart run build_runner build
    packageFilters:
      dependsOn: build_runner
    description: Run build_runner in packages that depend on it

  publish:dry:
    run: melos exec -- dart pub publish --dry-run
    packageFilters:
      private: false
    description: Dry run publish for all public packages

  publish:
    run: melos exec -- dart pub publish
    packageFilters:
      private: false
    description: Publish all public packages
